@startuml casos-de-uso
title Sistema de Moeda Estudantil - Diagrama de Casos de Uso
left to right direction
skinparam packageStyle rectangle
skinparam shadowing false

actor Usuario <<abstract>>
actor Aluno
actor Professor
actor "Empresa Parceira" as Empresa
actor "Servidor de\nE-mail" as Email <<sistema externo>>

rectangle "Sistema de Moeda Estudantil" {
  usecase "Realizar login" as UC01
  usecase "Cadastrar-se\n(aluno ou empresa)" as UC02
  usecase "Enviar moedas a um aluno" as UC03
  usecase "Consultar extrato" as UC04
  usecase "Trocar moedas por vantagem" as UC05
  usecase "Cadastrar vantagem" as UC06
  usecase "Conferir troca de vantagem" as UC07
  usecase "Enviar e-mail de notificacao" as UC09
}

Aluno --> UC02
Aluno --> UC04
Aluno --> UC05

Professor --> UC03
Professor --> UC04

Empresa --> UC02
Empresa --> UC06
Empresa --> UC07

Usuario --> UC01
Usuario <|-- Aluno
Usuario <|-- Professor
Usuario <|-- Empresa

UC09 --> Email

UC03 ..> UC09 : <<include>>
UC05 ..> UC09 : <<include>>



@enduml
