@startuml diagrama-de-componentes
title Sistema de Moeda Estudantil - Diagrama de Componentes
skinparam shadowing false
skinparam componentStyle uml2

package "Sistema de Moeda Estudantil" {
  [Interface Web\n(View)] as UI
  [Modulo de Autenticacao] as Auth
  [Modulo de Cadastro] as Cadastro
  [Modulo de Moedas] as Moedas
  [Modulo de Vantagens] as Vantagens
  [Modulo de Notificacao] as Notif
}

database "Banco de Dados" as DB
cloud "Servidor de E-mail\n(SMTP)" as SMTP

UI --> Auth
UI --> Cadastro
UI --> Moedas
UI --> Vantagens

Cadastro --> Auth
Moedas --> Auth
Vantagens --> Auth

Moedas --> Notif
Vantagens --> Notif

Auth --> DB
Cadastro --> DB
Moedas --> DB
Vantagens --> DB

Notif --> SMTP

@enduml
